{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsmasq-config
data:
  dnsmasq.conf: {{ .Values.configmap.dnsmasqConf }}
  resolve.conf: {{ .Values.configmap.resolvConf }}
{{- end }}