{{- if .Values.configmap.enabled }}
apiVersion: v1
kind: ConfigMap
metadata:
  name: dnsmasq-config
data:
  dnsmasq.conf: | 
    {{ .Values.configmap.dnsmasqConf | nindent 4 }}
  resolve.conf: |
    {{ .Values.configmap.resolvConf | nindent 4 }}
{{- end }}